CREATE TABLE Toronto_Plaques (
ID SERIAL,
Accession VARCHAR (20),
Plaque_Subject VARCHAR (100),
Year SMALLINT, 
Type VARCHAR(100),
Issuer VARCHAR(100),
Deaccessioned BOOLEAN,
Reproduction BOOLEAN,
Plaque_Text TEXT,
Has_Tranlated_Text BOOLEAN,
CCD SMALLINT,
Ward SMALLINT,
Address VARCHAR (100),
Longitude DOUBLE PRECISION,
Latitude DOUBLE PRECISION,
Material_Size VARCHAR (5),
Mount_Type VARCHAR (50),
Designated_Listed VARCHAR (5),
Status_Year SMALLINT,
Unveiling BOOLEAN,
Associated_Plaques TEXT,
Last_Maintenances VARCHAR (100),
Applicant VARCHAR(250),
Funding_1 VARCHAR(250),
Funding_2 VARCHAR(250),
Field_1 VARCHAR(250), --PDF URL
Notes TEXT,
Updated_By VARCHAR(250),
Updated_On DATE,
Tag VARCHAR (100),
Field_2 VARCHAR (250),
Thematic_Tag_1 VARCHAR (500),
Thematic_Tag_2 VARCHAR (500),
Thematic_Tag_3 VARCHAR (500),
Thematic_Tag_4 VARCHAR (500),
Temporal_Tag_1 VARCHAR (250),
Temporal_Tag_2 VARCHAR (250),
Temporal_Tag_3 VARCHAR (250),
Temporal_Tag_4 VARCHAR (250)
);
